/** Extended glossary — merged in glossary.ts */
export const additionalGlossaryTerms = [
  { term: "ADV filing", definition: "SEC Form ADV — public registration for investment advisers; source for CapSignal firm data." },
  { term: "Agent startup", definition: "Company building AI agents for workflows; distinct investor list from infra or vertical AI." },
  { term: "Angel investor", definition: "Individual investing personal capital, often at Pre-seed and Seed." },
  { term: "ARR", definition: "Annual recurring revenue — key SaaS metric for Seed investors." },
  { term: "Blast outreach", definition: "Identical email to hundreds of investors; low reply rates and deliverability risk." },
  { term: "Burn multiple", definition: "Net burn divided by net new ARR — efficiency metric investors watch." },
  { term: "Cap table", definition: "Ownership breakdown across founders, employees, and investors." },
  { term: "Carry", definition: "GP share of fund profits — CapSignal does not charge carry." },
  { term: "Co-investor", definition: "Another fund investing alongside in the same round." },
  { term: "Cold outreach", definition: "Email to investors without prior warm introduction." },
  { term: "Conversion funnel", definition: "Sent → opened → replied → meeting → diligence → close." },
  { term: "Data flywheel", definition: "AI moat from proprietary data improving model or product over time." },
  { term: "Day 0 email", definition: "First touch in an investor sequence — highest scrutiny from recipients." },
  { term: "Design partner", definition: "Early customer collaborating before full product — traction signal at Pre-seed." },
  { term: "Diligence", definition: "Investor review of metrics, references, legal, and product before term sheet." },
  { term: "Dilution", definition: "Ownership reduction from new investment and option pool expansion." },
  { term: "DMARC", definition: "Email authentication policy complementing SPF and DKIM." },
  { term: "Dry powder", definition: "Unallocated capital in a fund available for new investments." },
  { term: "Extension round", definition: "Additional capital within same priced round or on SAFE." },
  { term: "Foundation model", definition: "Large pretrained model — infra-layer AI category." },
  { term: "Fund vintage", definition: "Year a fund started investing — affects deployment urgency." },
  { term: "GP", definition: "General partner — decision-maker at a venture fund." },
  { term: "Hot intro", definition: "Strong endorsement from trusted mutual connection." },
  { term: "Inference cost", definition: "Per-request or per-user cost to run AI models — key AI unit economics." },
  { term: "Intro path", definition: "Mutual connection route to a target investor." },
  { term: "Lead magnet", definition: "Free resource offered to capture founder email — e.g. investor list guide." },
  { term: "LP", definition: "Limited partner — capital provider to a venture fund." },
  { term: "Meeting conversion", definition: "Percentage of replies that become scheduled calls." },
  { term: "Micro-VC", definition: "Small fund writing Pre-seed and Seed checks, often $250K–$2M." },
  { term: "Mutual connection", definition: "Person linked to both founder and investor on LinkedIn or portfolio graph." },
  { term: "NDA", definition: "Non-disclosure agreement — sometimes requested before data room access." },
  { term: "No-shop", definition: "Term sheet clause limiting founder from soliciting other offers for a period." },
  { term: "One-pager", definition: "Single-page company summary for investors post-meeting." },
  { term: "Open rate", definition: "Percentage of recipients who open an outreach email." },
  { term: "Option pool", definition: "Equity reserved for employee grants — often expanded at Seed." },
  { term: "Outreach batch", definition: "Group of investors contacted in the same send window." },
  { term: "Pass email", definition: "Investor decline — extract reason for future targeting." },
  { term: "Pipeline fiction", definition: "Inflated CRM stages without real investor engagement." },
  { term: "Portfolio overlap", definition: "Shared investments between target investor and comparable companies." },
  { term: "Pre-emptive offer", definition: "Investor term sheet before formal fundraise process." },
  { term: "Pro-rata", definition: "Right to invest in future rounds to maintain ownership." },
  { term: "Raise profile", definition: "CapSignal input: stage, sector, traction, target amount, preferences." },
  { term: "Reply detection", definition: "Automatic pause of sequence when investor responds." },
  { term: "SAFE", definition: "Simple Agreement for Future Equity — common Pre-seed instrument." },
  { term: "Second meeting", definition: "Partner + associate or full partnership — diligence signal." },
  { term: "Send throttling", definition: "Limiting daily email volume to protect domain reputation." },
  { term: "Series A crunch", definition: "Gap between Seed metrics bar and Series A expectations." },
  { term: "Spray and pray", definition: "High-volume untargeted outreach — avoid." },
  { term: "Syndicate", definition: "Multiple investors participating in one round." },
  { term: "Term sheet", definition: "Outline of investment terms before definitive docs." },
  { term: "Thesis drift", definition: "When investor's actual deals diverge from stated focus." },
  { term: "Thesis hook", definition: "Opening line referencing investor's portfolio or focus." },
  { term: "Trial period", definition: "CapSignal 7-day free trial before monthly billing." },
  { term: "Unit economics", definition: "Revenue and cost per customer or transaction." },
  { term: "Valuation cap", definition: "SAFE ceiling for conversion price in future priced round." },
  { term: "Vertical AI", definition: "AI product built for one industry workflow." },
  { term: "Warm path", definition: "Introduction route via portfolio founder or mutual." },
  { term: "Weekly iteration", definition: "CapSignal campaign adjustments based on reply data." },
] as const;
