export const glossaryTerms = [
  { term: "Deployment signal", definition: "Evidence an investor is actively writing checks—recent investments, follow-ons, or fund close announcements." },
  { term: "Thesis fit", definition: "Alignment between an investor's stated sector/stage focus and your company's category and round." },
  { term: "Match score", definition: "CapSignal's 0–100 ranking of investor fit for your specific raise, with written rationale." },
  { term: "Sequence", definition: "A multi-step outreach cadence (typically 3–5 emails) sent to one investor over 2–3 weeks." },
  { term: "Reply rate", definition: "Percentage of contacted investors who respond by email. Tracked per campaign from your outreach data." },
  { term: "Send window", definition: "Optimal days/times for outreach based on investor timezone and historical open data." },
  { term: "Shortlist", definition: "Ranked list of target investors approved before campaign launch." },
  { term: "Signal layer", definition: "One of four data categories—deployment, thesis, engagement, network—used in scoring." },
  { term: "SPF/DKIM", definition: "Email authentication records that improve deliverability when sending from your domain." },
  { term: "Warm intro", definition: "Introduction through a mutual connection. CapSignal maps potential paths via portfolio overlap." },
  { term: "Follow-on", definition: "Additional investment in an existing portfolio company—signals sector conviction." },
  { term: "Check size", definition: "Typical investment amount an investor or fund deploys per deal." },
  { term: "Data room", definition: "Secure folder of diligence materials—deck, model, cap table, legal docs." },
  { term: "Term sheet", definition: "Non-binding document outlining investment terms before definitive agreements." },
  { term: "Lead investor", definition: "Primary investor setting round terms and often taking the largest check." },
  { term: "Party round", definition: "Raise with many small investors and no clear lead—often harder to close." },
  { term: "Signal refresh", definition: "Nightly recalculation of investor activity scores from new data." },
  { term: "Engagement signal", definition: "Reply patterns, subject line performance, and send timing data from prior campaigns." },
  { term: "Exclusion list", definition: "Investors flagged to never receive outreach—conflicts, prior passes, existing relationships." },
  { term: "Campaign", definition: "One fundraising outreach effort with defined shortlist, sequences, and timeline." },
] as const;
