import type { Guide } from "./resources";

/** Additional guides — merged into main guides array for ~10× resource depth. */
export const additionalGuides: Guide[] = [
  {
    slug: "ai-seed-investors-still-writing-checks",
    title: "AI Seed investors still writing checks in 2026",
    description: "How to find active AI/ML funds when headlines say 'funding is frozen.'",
    category: "Fundraising strategy",
    readTime: "14 min",
    published: "2026-06-01",
    sections: [
      { heading: "Deployment vs. headlines", body: "Many AI funds are deploying from 2023–2024 vintages even when new fund announcements slow. Follow-ons and new checks in infra and vertical AI continue — filter by recorded investments in the last two quarters." },
      { heading: "Sub-sector matters", body: "Infra and dev tools see different investors than consumer AI wrappers. Agent platforms sit between — match on portfolio, not buzzwords." },
      { heading: "Using CapSignal for AI", body: "Select AI/ML in your raise profile; review match rationale citing recent deals. Exclude funds with no AI deployment in 18+ months." },
      { heading: "Outreach angle", body: "Reference a specific portfolio company and one metric — inference cost, design partners, or model benchmark — not 'we're the ChatGPT for X.'" },
    ],
  },
  {
    slug: "raise-ai-agents-startup",
    title: "Raising for an AI agents startup",
    description: "Investor expectations, traction bars, and messaging for agent companies.",
    category: "Fundraising strategy",
    readTime: "11 min",
    published: "2026-05-20",
    sections: [
      { heading: "What investors want to see", body: "Workflow depth, retention on agent tasks, human-in-the-loop design, and defensibility beyond a thin GPT wrapper. Enterprise design partners beat vanity user counts." },
      { heading: "Investor list", body: "Target funds with agent or automation portfolio overlap — not every 'AI fund' writes agent checks." },
      { heading: "Common pass reasons", body: "'Feature not company,' commoditized orchestration layer, unclear unit economics on tool calls and inference." },
    ],
  },
  {
    slug: "ai-infra-vs-vertical-ai-fundraising",
    title: "Fundraising for AI infra vs. vertical AI",
    description: "Different investors, metrics, and narratives for infra and application-layer AI.",
    category: "Data & targeting",
    readTime: "10 min",
    published: "2026-05-15",
    sections: [
      { heading: "Infra narrative", body: "Technical moat, performance benchmarks, developer adoption, open-source traction, and path to platform revenue." },
      { heading: "Vertical AI narrative", body: "Industry-specific workflow, ACV, sales cycle, regulatory context, and incumbent displacement — not model architecture alone." },
      { heading: "Match split", body: "Run separate investor tiers or campaigns if you span both; mixed messaging confuses partners." },
    ],
  },
  {
    slug: "founder-led-investor-outreach-guide",
    title: "The complete founder-led investor outreach guide",
    description: "End-to-end playbook from AI matching to term sheet without an advisor.",
    category: "Outreach",
    readTime: "18 min",
    published: "2026-04-01",
    sections: [
      { heading: "Phase 1: Profile", body: "Document stage, sector, traction, raise amount, and exclusions (conflicts, prior passes)." },
      { heading: "Phase 2: AI matching", body: "200–400 scored investors with rationale. Founder approves every row." },
      { heading: "Phase 3: Messaging", body: "Thesis hooks per top 50; template structure for long tail with personalization tokens." },
      { heading: "Phase 4: Launch", body: "Batch sends Tue–Thu mornings investor-local. Monitor bounces and replies daily." },
      { heading: "Phase 5: Pipeline", body: "Meeting recaps within 24h. Weekly review of stalled deals." },
    ],
  },
  {
    slug: "investor-meeting-prep-checklist",
    title: "Investor meeting prep checklist",
    description: "What to prepare before every partner call.",
    category: "Investor relations",
    readTime: "7 min",
    published: "2026-03-22",
    sections: [
      { heading: "Research", body: "Last three investments, partner's public posts, portfolio conflicts, typical check size." },
      { heading: "Materials", body: "Deck, one-pager, model ready in data room — send link after call if requested, not before." },
      { heading: "Ask", body: "Clear next step: second partner, customer reference, or diligence timeline." },
    ],
  },
  {
    slug: "term-sheet-basics-founders",
    title: "Term sheet basics for first-time founders",
    description: "Key terms to understand before signing.",
    category: "Fundraising strategy",
    readTime: "15 min",
    published: "2026-02-10",
    sections: [
      { heading: "Economics", body: "Valuation, option pool shuffle, pro-rata rights. Understand fully diluted ownership." },
      { heading: "Control", body: "Board composition, protective provisions, information rights." },
      { heading: "When to hire counsel", body: "Before signing — not after. Cap table complexity increases cost." },
    ],
  },
  {
    slug: "warm-intro-vs-cold-outreach",
    title: "Warm intros vs. cold outreach — when each wins",
    description: "How to combine intros and outbound in one raise.",
    category: "Outreach",
    readTime: "9 min",
    published: "2026-04-18",
    sections: [
      { heading: "Warm intros", body: "Highest conversion but limited supply. Map portfolio founder paths from overlap data." },
      { heading: "Cold outreach", body: "Scales volume; thesis-aware copy closes gap with warm. Many Seed rounds are 70% cold, 30% intro." },
      { heading: "Sequencing", body: "Don't cold email an investor the same week a mutual connection intro'd you." },
    ],
  },
  {
    slug: "investor-update-emails-during-raise",
    title: "Investor update emails during an active raise",
    description: "Keep warm investors informed without oversharing.",
    category: "Investor relations",
    readTime: "6 min",
    published: "2026-01-28",
    sections: [
      { heading: "Who gets updates", body: "Investors in diligence, soft circles, and advisors — not your full cold list." },
      { heading: "Content", body: "One metric movement, one customer win, round status if appropriate. Monthly max." },
    ],
  },
  {
    slug: "deliverability-founder-email",
    title: "Email deliverability for founder outreach",
    description: "SPF, DKIM, volume limits, and domain warming.",
    category: "Outreach",
    readTime: "10 min",
    published: "2026-03-08",
    sections: [
      { heading: "Authentication", body: "SPF and DKIM on sending domain required. CapSignal configures records during onboarding." },
      { heading: "Volume", body: "Ramp sends — 20–40 per day initially for new domains. Sudden spikes trigger spam filters." },
      { heading: "Content", body: "Avoid spam triggers: all caps, excessive links, image-only emails, attachment on cold send." },
    ],
  },
  {
    slug: "series-a-fundraising-playbook",
    title: "Series A fundraising playbook",
    description: "Higher bar, longer cycle, lead investor focus.",
    category: "Fundraising strategy",
    readTime: "16 min",
    published: "2026-02-25",
    sections: [
      { heading: "Metrics bar", body: "Series A investors expect repeatable revenue or strong usage growth with unit economics story." },
      { heading: "Lead-first", body: "Identify 15–25 lead candidates; run parallel diligence tracks once lead emerges." },
      { heading: "Timeline", body: "10–16 weeks typical. Start before you 'need' capital by 3 months." },
    ],
  },
  {
    slug: "angel-vs-vc-seed",
    title: "Angels vs. VCs at Seed — who to target first",
    description: "Check size, speed, and signaling considerations.",
    category: "Fundraising strategy",
    readTime: "8 min",
    published: "2026-01-15",
    sections: [
      { heading: "Angels", body: "Faster decisions, smaller checks, valuable for first $500K–$1M. Often sector operators." },
      { heading: "VCs", body: "Lead capability, follow-on reserve, board seat. Better for $2M+ Seeds." },
      { heading: "Order", body: "Many founders close angels first for traction signal, then VC lead." },
    ],
  },
  {
    slug: "investor-pass-reasons-patterns",
    title: "Common investor pass reasons and how to fix them",
    description: "Patterns from Seed outreach and positioning fixes.",
    category: "Investor relations",
    readTime: "12 min",
    published: "2026-05-05",
    sections: [
      { heading: "Timing", body: "Fund not deploying, partner bandwidth, end of fund life — not fixable; move on." },
      { heading: "Thesis", body: "Wrong sector or stage — fix your matches, not pitch." },
      { heading: "Traction", body: "Too early — delay raise or show design partners and LOIs." },
      { heading: "Competition", body: "Crowded space — sharpen differentiation and incumbent wedge." },
    ],
  },
  {
    slug: "pitch-deck-seed-structure",
    title: "Seed pitch deck structure that converts",
    description: "Slide order and content investors expect in 2026.",
    category: "Fundraising strategy",
    readTime: "11 min",
    published: "2026-04-05",
    sections: [
      { heading: "Opening", body: "Problem, solution, why now — one slide each. No team slide first." },
      { heading: "Traction", body: "Metrics slide before market size. Investors trust what you've done over TAM slides." },
      { heading: "Ask", body: "Amount, use of funds, 18-month milestones. Clear and specific." },
    ],
  },
  {
    slug: "cap-table-before-seed",
    title: "Cap table hygiene before Seed",
    description: "Clean up before investors diligence.",
    category: "Fundraising strategy",
    readTime: "9 min",
    published: "2026-03-12",
    sections: [
      { heading: "Common issues", body: "Informal advisor equity, missing 83(b), duplicate SAFEs, unclear option pool." },
      { heading: "Fix first", body: "Resolve before data room — surprises kill deals in diligence." },
    ],
  },
  {
    slug: "fundraising-during-product-market-fit",
    title: "Fundraising while searching for product-market fit",
    description: "When to raise pre-PMF and how to position.",
    category: "Fundraising strategy",
    readTime: "10 min",
    published: "2026-02-01",
    sections: [
      { heading: "Pre-PMF investors", body: "Pre-seed funds and angels bet on team and market — target them, not growth-stage VCs." },
      { heading: "Honest narrative", body: "Design partners and learning velocity beat inflated metrics." },
    ],
  },
  {
    slug: "geo-targeting-investors",
    title: "Geographic targeting in investor outreach",
    description: "Local vs. national investor prioritization.",
    category: "Data & targeting",
    readTime: "7 min",
    published: "2026-05-08",
    sections: [
      { heading: "Local first", body: "Regional funds often move faster and take meetings in person. CapSignal prioritizes metro activity from raise profile city." },
      { heading: "National expansion", body: "After local batch, expand to SF/NYC funds with remote-friendly thesis." },
    ],
  },
  {
    slug: "duplicate-investor-outreach-mistakes",
    title: "7 outreach mistakes that kill reply rates",
    description: "Fixable errors founders make on first campaigns.",
    category: "Outreach",
    readTime: "8 min",
    published: "2026-04-22",
    sections: [
      { heading: "Generic openers", body: "No portfolio reference or sector specificity." },
      { heading: "Attachments on cold send", body: "Hurts deliverability; earn the meeting first." },
      { heading: "Wrong stage fit", body: "Series B funds on Pre-seed lists waste everyone's time." },
      { heading: "No follow-up", body: "Single email leaves 60%+ of eventual replies on the table." },
    ],
  },
  {
    slug: "investor-data-room-checklist",
    title: "Investor data room checklist",
    description: "Documents to include before diligence.",
    category: "Fundraising strategy",
    readTime: "8 min",
    published: "2026-01-20",
    sections: [
      { heading: "Core", body: "Deck, one-pager, model, cap table, incorporation, IP assignments." },
      { heading: "Optional early", body: "Customer references, pipeline, technical architecture for deep tech." },
      { heading: "Permissions", body: "View tracking per investor — CapSignal data room supports access controls." },
    ],
  },
  {
    slug: "post-demo-day-fundraising",
    title: "Post-demo-day fundraising follow-up",
    description: "Convert demo day interest into meetings.",
    category: "Outreach",
    readTime: "9 min",
    published: "2026-06-10",
    sections: [
      { heading: "48-hour window", body: "Follow up while memory is fresh. Reference demo day conversation specifically." },
      { heading: "Segment", body: "Hot leads get personal note; warm get sequence; cold get standard cadence." },
    ],
  },
  {
    slug: "saas-seed-metrics-investors-want",
    title: "SaaS metrics Seed investors ask about",
    description: "ARR, growth, retention, and efficiency benchmarks.",
    category: "Fundraising strategy",
    readTime: "12 min",
    published: "2026-03-28",
    sections: [
      { heading: "Core metrics", body: "MRR/ARR, growth rate, net revenue retention, CAC payback, gross margin." },
      { heading: "Stage expectations", body: "Pre-seed: design partners. Seed: $500K–$2M ARR or strong usage growth with pricing path." },
    ],
  },
  {
    slug: "fintech-fundraising-narrative",
    title: "Fundraising narrative for fintech startups",
    description: "Regulatory context and investor segmentation.",
    category: "Fundraising strategy",
    readTime: "11 min",
    published: "2026-02-18",
    sections: [
      { heading: "Sub-sectors", body: "Payments, lending, banking infra, insurtech — different investor lists." },
      { heading: "Compliance", body: "Address regulatory path early in email and deck — don't hide complexity." },
    ],
  },
  {
    slug: "climate-tech-investor-targeting",
    title: "Climate tech investor targeting",
    description: "Hardware vs. software climate investors.",
    category: "Data & targeting",
    readTime: "10 min",
    published: "2026-01-30",
    sections: [
      { heading: "Verify deployment", body: "Many funds market climate; fewer deploy. Use investment records, not website copy." },
      { heading: "Software climate", body: "Often overlaps B2B SaaS investors — dual track match pools." },
    ],
  },
  {
    slug: "repeat-founder-fundraising",
    title: "Fundraising as a repeat founder",
    description: "Leveraging track record without resting on it.",
    category: "Fundraising strategy",
    readTime: "8 min",
    published: "2026-05-25",
    sections: [
      { heading: "Advantages", body: "Prior investor network, faster diligence, credibility on execution." },
      { heading: "Pitfalls", body: "Assuming old relationships convert without outreach; wrong stage investors from last company." },
    ],
  },
  {
    slug: "solo-founder-fundraising",
    title: "Fundraising as a solo founder",
    description: "Addressing investor bias and building confidence.",
    category: "Fundraising strategy",
    readTime: "9 min",
    published: "2026-04-12",
    sections: [
      { heading: "Investor concerns", body: "Bandwidth, key-person risk, hiring plan — address proactively in deck and email." },
      { heading: "Advisors", body: "Strategic advisors with domain credibility help; don't overstate involvement." },
    ],
  },
  {
    slug: "investor-conference-follow-up",
    title: "Converting conference contacts into meetings",
    description: "Follow-up playbook after investor events.",
    category: "Outreach",
    readTime: "6 min",
    published: "2026-03-05",
    sections: [
      { heading: "Same week", body: "Email referencing booth conversation or panel. LinkedIn only if they're active there." },
      { heading: "CRM", body: "Log source as conference — measure conversion vs. cold for ROI on events." },
    ],
  },
  {
    slug: "board-construction-seed",
    title: "Board construction at Seed",
    description: "When to add investor board seats.",
    category: "Investor relations",
    readTime: "7 min",
    published: "2026-02-08",
    sections: [
      { heading: "Typical Seed board", body: "2 founders + 1 investor or observer. Keep it small." },
      { heading: "Negotiation", body: "Board seat often tied to lead check — not every investor gets a seat." },
    ],
  },
  {
    slug: "safe-vs-priced-round",
    title: "SAFE vs. priced Seed round",
    description: "When each instrument makes sense.",
    category: "Fundraising strategy",
    readTime: "10 min",
    published: "2026-01-05",
    sections: [
      { heading: "SAFE", body: "Faster close, fewer legal fees, common for pre-seed and small Seed extensions." },
      { heading: "Priced", body: "Lead investor, clearer ownership, required for larger Seed rounds with syndicate." },
    ],
  },
  {
    slug: "investor-rejection-follow-up",
    title: "When to follow up after an investor passes",
    description: "Staying on radar without being annoying.",
    category: "Investor relations",
    readTime: "5 min",
    published: "2026-04-30",
    sections: [
      { heading: "Timing", body: "Quarterly update if they asked to 'stay in touch.' Major milestone only otherwise." },
      { heading: "Re-engage", body: "New round or step-change traction — new email thread, reference prior pass reason." },
    ],
  },
  {
    slug: "competitive-fundraising-process",
    title: "Running a competitive fundraising process",
    description: "Creating momentum without manufactured FOMO.",
    category: "Fundraising strategy",
    readTime: "11 min",
    published: "2026-03-18",
    sections: [
      { heading: "Parallel tracks", body: "Multiple diligences in flight — legitimate urgency, not bluffing." },
      { heading: "Transparency", body: "Don't lie about term sheets. Investors talk to each other." },
    ],
  },
  {
    slug: "investor-reference-calls",
    title: "Preparing for investor reference calls",
    description: "Customer and founder references diligence expects.",
    category: "Investor relations",
    readTime: "8 min",
    published: "2026-02-22",
    sections: [
      { heading: "Who to prep", body: "2–3 customers, co-founder if applicable, prior investors for repeat founders." },
      { heading: "Brief them", body: "Share metrics they'll be asked about; align on narrative." },
    ],
  },
  {
    slug: "fundraising-burn-multiple",
    title: "Burn multiple and runway in investor conversations",
    description: "How investors evaluate efficiency at Seed.",
    category: "Fundraising strategy",
    readTime: "9 min",
    published: "2026-05-18",
    sections: [
      { heading: "Runway", body: "18–24 months post-raise is standard plan. Show path to milestones on raised capital." },
      { heading: "Efficiency", body: "Net burn vs. net new ARR — especially relevant in 2026 SaaS Seed." },
    ],
  },
  {
    slug: "linkedin-investor-research",
    title: "Using LinkedIn for investor research",
    description: "Partner activity signals before outreach.",
    category: "Data & targeting",
    readTime: "7 min",
    published: "2026-04-08",
    sections: [
      { heading: "Signals", body: "Recent posts on your sector, new portfolio announcements, job changes." },
      { heading: "Outreach tie-in", body: "Reference LinkedIn content only if genuine — not 'loved your post about leadership.'" },
    ],
  },
  {
    slug: "investor-email-subject-lines",
    title: "Investor email subject lines that get opens",
    description: "Tested patterns for cold investor email.",
    category: "Outreach",
    readTime: "6 min",
    published: "2026-03-25",
    sections: [
      { heading: "Works", body: "Sector + portfolio ref: 'AI infra — parallel to [Co]'. Stage + traction: 'Seed — $1.2M ARR workflow automation'." },
      { heading: "Avoid", body: "'Intro request', 'Quick chat', 'Investment opportunity', all lowercase gimmicks." },
    ],
  },
  {
    slug: "multilingual-founder-us-raise",
    title: "International founders raising in the US",
    description: "Targeting US investors from abroad.",
    category: "Fundraising strategy",
    readTime: "10 min",
    published: "2026-01-25",
    sections: [
      { heading: "Delaware C-Corp", body: "Standard expectation for US VC. Have structure ready before outreach." },
      { heading: "Timezone", body: "CapSignal send windows adjust for investor local time; founders should offer US-friendly meeting slots." },
    ],
  },
  {
    slug: "investor-crm-vs-spreadsheet",
    title: "Outgrowing the fundraising spreadsheet",
    description: "When to move to investor CRM.",
    category: "Investor relations",
    readTime: "6 min",
    published: "2026-06-05",
    sections: [
      { heading: "Break points", body: "100+ contacts, multiple founders emailing, lost follow-ups, no reply tracking." },
      { heading: "Migration", body: "Import CSV to CapSignal; map stages; link to active sequences." },
    ],
  },
  {
    slug: "week-one-fundraising-metrics",
    title: "Metrics to track in week one of outreach",
    description: "Open, reply, and meeting rates benchmarks.",
    category: "Outreach",
    readTime: "7 min",
    published: "2026-05-02",
    sections: [
      { heading: "Benchmarks", body: "Seed cold: 2–4% reply baseline; thesis-aware often 6–12%. Meeting rate ~25–40% of replies." },
      { heading: "Adjust", body: "Low opens → subject lines. Low replies → copy or list quality. Low meetings → traction or ask clarity." },
    ],
  },
  {
    slug: "investor-thesis-pages-how-to-read",
    title: "How to read investor thesis pages",
    description: "Separate marketing from actual deployment.",
    category: "Data & targeting",
    readTime: "9 min",
    published: "2026-02-15",
    sections: [
      { heading: "Marketing vs. reality", body: "Compare thesis page to last 10 investments on record — often diverge." },
      { heading: "Archive check", body: "Wayback Machine for thesis shifts — new AI emphasis may mean active deployment." },
    ],
  },
  {
    slug: "fundraising-without-network",
    title: "Raising without a warm network",
    description: "Cold-outbound-first strategies that work.",
    category: "Outreach",
    readTime: "10 min",
    published: "2026-04-15",
    sections: [
      { heading: "Volume + quality", body: "Cold works at Seed — you need both list quality and personalization." },
      { heading: "Proof points", body: "Traction and specificity compensate for no intro." },
    ],
  },
  {
    slug: "investor-outreach-tools-compared",
    title: "Investor outreach tools compared (2026)",
    description: "CapSignal, OpenVC, Harmonic, CRMs, and advisors.",
    category: "Data & targeting",
    readTime: "13 min",
    published: "2026-06-15",
    sections: [
      { heading: "Directories", body: "OpenVC, Crunchbase — research, no execution." },
      { heading: "Search platforms", body: "Harmonic — discovery and network graph." },
      { heading: "Execution", body: "CapSignal — matching + outreach + CRM + data room." },
      { heading: "Advisors", body: "High touch, high cost, variable scalability." },
    ],
  },
  {
    slug: "ai-founder-pitch-mistakes",
    title: "AI founder pitch mistakes in 2026",
    description: "What AI investors are tired of hearing.",
    category: "Fundraising strategy",
    readTime: "9 min",
    published: "2026-06-20",
    sections: [
      { heading: "Wrapper fatigue", body: "Thin GPT UI without moat — lead with data, workflow, or distribution." },
      { heading: "TAM slides", body: "Every AI deck cites the same market size — investors want your wedge." },
      { heading: "Ignore unit economics", body: "Inference cost and gross margin matter at Seed for AI." },
    ],
  },
];
